services:

    traefik:
        image: traefik:3.3
        container_name: traefik
        restart: always
        command:
            - --providers.docker=true
            - --providers.docker.exposedByDefault=false
            - --entryPoints.http.address=:80
            - --entryPoints.https.address=:443
            - --certificatesResolvers.letsEncrypt.acme.httpChallenge=true
            - --certificatesResolvers.letsEncrypt.acme.httpChallenge.entryPoint=http
            - --certificatesResolvers.letsEncrypt.acme.email=mail@zay.media
            - --certificatesResolvers.letsEncrypt.acme.storage=/certs/acme.json
        ports:
            - target: 80
              published: 80
              protocol: tcp
              mode: host
            - target: 443
              published: 443
              protocol: tcp
              mode: host
        networks:
            - traefik-public
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock:ro
            - traefik-public-certs:/certs
        labels:
            - traefik.enable=true
            - traefik.docker.network=traefik-public

            - traefik.http.routers.http-catchall.rule=HostRegexp(`.+`)
            - traefik.http.routers.http-catchall.entryPoints=http
            - traefik.http.routers.http-catchall.middlewares=redirect-to-https
            - traefik.http.services.http-catchall.loadBalancer.server.port=80

            - traefik.http.middlewares.redirect-to-https.redirectScheme.scheme=https
            - traefik.http.middlewares.redirect-to-https.redirectScheme.permanent=true

            - traefik.http.middlewares.secure-headers.headers.sslRedirect=true
            - traefik.http.middlewares.secure-headers.headers.stsSeconds=31536000
            - traefik.http.middlewares.secure-headers.headers.contentSecurityPolicy=block-all-mixed-content

volumes:
    traefik-public-certs:

networks:
    traefik-public:
        external: true
