services:

    rabbitmq:
        container_name: rabbitmq
        restart: always
        image: rabbitmq:3-management
        ports:
            - "5672:5672"
        environment:
            RABBITMQ_DEFAULT_USER: "guest"
            RABBITMQ_DEFAULT_PASS: "guest"
        volumes:
            - rabbitmq-data:/var/lib/rabbitmq
        networks:
            - traefik-public
        labels:
            - traefik.enable=true
            - traefik.docker.network=traefik-public
            - traefik.http.routers.rabbitmq.rule=Host(`rabbit.zay.media`)
            - traefik.http.routers.rabbitmq.entryPoints=https
            - traefik.http.routers.rabbitmq.middlewares=secure-headers
            - traefik.http.routers.rabbitmq.tls=true
            - traefik.http.routers.rabbitmq.tls.certResolver=letsEncrypt
            - traefik.http.services.rabbitmq.loadBalancer.server.port=15672

volumes:
    rabbitmq-data:

networks:
    traefik-public:
        external: true
