services:

  jenkins:
    container_name: jenkins
    restart: always
    build:
      context: ./docker
    environment:
      DOCKER_HOST: tcp://docker:2376
      DOCKER_CERT_PATH: /certs/client
      DOCKER_TLS_VERIFY: 1
    volumes:
      - jenkins-data:/var/jenkins_home
      - docker-certs:/certs/client:ro
    depends_on:
      - docker
    networks:
      - traefik-public
      - default
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik-public
      - traefik.http.routers.jenkins.rule=Host(`jenkins.zay.media`)
      - traefik.http.routers.jenkins.entryPoints=https
      - traefik.http.routers.jenkins.middlewares=secure-headers
      - traefik.http.routers.jenkins.tls=true
      - traefik.http.routers.jenkins.tls.certResolver=letsEncrypt

  docker:
    container_name: docker
    image: docker:dind
    restart: always
    privileged: true
    environment:
      DOCKER_TLS_CERTDIR: /certs
    volumes:
      - jenkins-data:/var/jenkins_home
      - docker-certs:/certs/client
      - docker-data:/var/lib/docker

volumes:
  jenkins-data:
  docker-certs:
  docker-data:

networks:
  traefik-public:
    external: true
