services:

    portainer:
        container_name: portainer
        restart: always
        image: portainer/portainer-ce:latest
        volumes:
            - portainer_data:/data
            - /var/run/docker.sock:/var/run/docker.sock
        networks:
            - traefik-public
        labels:
            - traefik.enable=true
            - traefik.docker.network=traefik-public
            - traefik.http.routers.portainer.rule=Host(`portainer.zay.media`)
            - traefik.http.routers.portainer.entryPoints=https
            - traefik.http.routers.portainer.middlewares=secure-headers
            - traefik.http.routers.portainer.tls=true
            - traefik.http.routers.portainer.tls.certResolver=letsEncrypt
            - traefik.http.services.portainer.loadBalancer.server.port=9000

networks:
    traefik-public:
        external: true

volumes:
    portainer_data:
