services:

  postgres:
    container_name: postgres
    restart: unless-stopped
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "user-password"
      POSTGRES_DB: "db-name"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
